config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #get 'stock/index'
  #get 'blogs/index'
  get 'blogs', to:'blogs#index'
  get 'stocks', to:'stocks#index'
  root :to => 'blogs#top'
  resources :blogs do
    collection do
      post:confirm
    end
  end
  resources :users, only: [:new, :create, :show]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :favorites, only: [:create, :destroy]

  #if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  #end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { in: 1..20 }
  validates :content, presence: true, length: { in: 1..140 }
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/company.rb
class Company < ApplicationRecord
   has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :show, :new, :destroy]
  
  def index
    @blogs = Blog.all
    #raise
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def confirm
    @blog = Blog.new(blog_params) 
    @blog.user_id = current_user.id
    #p @blog
    render :new if @blog.invalid?
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def edit
  end
  
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.image.retrieve_from_cache!  params[:cache][:image] 
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
   
    if @blog.save
      BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください！"
      redirect_to login_url
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to login_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="blog_title">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下内容で送信する</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>
<div class="row">
  <% @blogs.each do |blog| %>
    <div class="col-xs-12 col-md-6 blog-panel">
      <h2><%= blog.title%></h2>
      <p><%= blog.content%></p>
      <p><%= blog.created_at %></p>
      <div class="blog-links">
        <%= link_to '詳細', blog, class: 'btn btn-default' %>
        <% if blog.user_id == current_user.id  %>
          <%= link_to '編集', edit_blog_path(blog), class: 'btn btn-info'  %> |
          <%= link_to '削除', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<!--
<div class="container">
  <header class="header">Bootstrap<span class="label label-success">Challenge!!</spna></header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap</a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav>
<article>
    <div class="contents">
      <div class="row">

        <div class="col-md-6">
          <ul class="row_A">
            <li class="col-sm-6 col-md-3">contents1</li>
            <li class="col-sm-6 col-md-offset-1 col-md-8">contents2</li>
            <li class="col-sm-6 col-md-5">contents3</li>
            <li class="col-sm-6 col-md-offset-2 col-md-5">contents4</li>
          </ul>
        </div>

        <div class="col-md-6">
          <div class="topic">
            <ul class="row_B">
              <li class="col-md-12">bootstrapを使ってレスポンシブデザインを実現しよう！</li>
              <li class="col-md-12">やればできる！bootstrapを使ってみよう！</li>
              <li class="col-md-12">怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に!</li>
            </ul>
          </div>
        </div>

      </div>
    </div>
  </article>
</div>
-->

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/blogs/top.html.erb
<section class="about">
  <div class="mainphoto">
    <%= image_tag "mysons.jpg", class:"img-responsive"%>
  </div>
</section>
<section>
  <h1>豊富なラインナップ</h1>
  <div class="row">
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag "gogatsubyou_kids.png" %>
        <div class="caption">
          <h3>工作体験</h3>
          <p>...</p>
          <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag "kashiwamochi_boy.png" %>
        <div class="caption">
          <h3>手作りお菓子</h3>
          <p>...</p>
          <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag "kodomonohi_yoroi_kabuto.png" %>
        <div class="caption">
          <h3>たたかいごっこ</h3>
          <p>...</p>
          <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag "koinobori_boy_girl.png" %>
        <div class="caption">
          <h3>みんなでワイワイ</h3>
          <p>...</p>
          <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>エンジョイジャパン株式会社</li>
      <li>© 2018 Copyright Enjoy Japan Corp.</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-md-6">
        <%= link_to "NoNJapa", root_path, id:"logo" %>
      </div>
      <div class="col-xs-6 col-md-6">
        <nav>
          <div class="row_add">
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li class="col-xs-4 col-md-4"><%= link_to "新規投稿", new_blog_path %></li>
                <li class="col-xs-4 col-md-4"><%= link_to "投稿一覧", blogs_path %></li>
                <li class="col-xs-4 col-md-4"><%= link_to "ログアウ", logout_path(current_user.id), method: :delete %></li>
              <% else %>
                <li class:"col-xs-6"><%= link_to "新規登録", new_user_path %></li>
                <li class:"col-xs-6"><%= link_to "ログイン", login_path %></li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div class="main_field"></div>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<div>
<p>メールアドレス: <%= @user.email %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @user.image %>
</p>


<% @favorites_blogs = @user.favorite_blogs %>
  <div>
  <% @favorites_blogs.each do |favorites_blog| %>
    <div class="col-xs-12 col-md-6 blog-panel">
      <h2><%= favorites_blog.title%></h2>
      <p><%= favorites_blog.content%></p>
      <p><%= favorites_blog.created_at %></p>
      <div class="blog-links">
        <%= link_to '詳細', favorites_blog, class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
  </div>
</div>